pipeline {
  environment {
    registry = "akshathadocker/dockerhub_pipeline_repository"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Run Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            "docker run ${dockerImage}"
          }
        }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    
  }
}
